version: "3.7"
services:
  web:
    build: .
    container_name: frontend
    working_dir: /app
    environment:
        - WEB_DOCUMENT_ROOT=/app/public/
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - api
      - default
networks:
  api:
    name: backend_default