version: "3.7"
services:
  project:
    build: .
    container_name: prinder-api
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
      - COMPOSER_VERSION=2
      - JWT_PRIVATE_KEY=h4Bvt_+=vCbxv|&]@^0ce,}:PnH~2%c%%%3?nOvl8@0DxfCh35RNy=?r1R_BMj_l
    ports:
      - 8082:80
  db:
    image: mysql
    container_name: prinder-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app_dev
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql-data:
    external: true
    name: prinder-database